<?php

namespace Twovmodules\RevenueCat\Enum;

enum WebHookEventType: string
{
    case TEST = 'TEST';
    case INITIAL_PURCHASE = 'INITIAL_PURCHASE';
    case RENEWAL = 'RENEWAL';
    case CANCELLATION = 'CANCELLATION';
    case UNCANCELLATION = 'UNCANCELLATION';
    case NON_RENEWING_PURCHASE = 'NON_RENEWING_PURCHASE';
    case SUBSCRIPTION_PAUSED = 'SUBSCRIPTION_PAUSED';
    case EXPIRATION = 'EXPIRATION';
    case BILLING_ISSUE = 'BILLING_ISSUE';
    case PRODUCT_CHANGE = 'PRODUCT_CHANGE';
    case TRANSFER = 'TRANSFER';
    case SUBSCRIPTION_EXTENDED = 'SUBSCRIPTION_EXTENDED';
    case TEMPORARY_ENTITLEMENT_GRANT = 'TEMPORARY_ENTITLEMENT_GRANT';
    case INVOICE_ISSUANCE = 'INVOICE_ISSUANCE';
    case SUBSCRIBER_ALIAS = 'SUBSCRIBER_ALIAS';
}
