name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    steps:
      - name: Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check coding style via ECS
        run: vendor/bin/ecs check

      - name: Check coding style via Rector
        run: vendor/bin/rector process --memory-limit=1G --dry-run --ansi

      - name: Run static analysis via PHPStan
        run: vendor/bin/phpstan analyse src tests

      - name: Run tests
        run: vendor/bin/phpunit --testdox
